# 
# policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/ckpts/policy_0.85_extended.pt"
# stand_policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/ckpts/policy_0.85_extended.pt"
policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/g1/policy_0.85.pt"
stand_policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/g1/policy_0.85.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/g1_description/g1_23dof_rev_1_0.xml"

# Total simulation time
simulation_duration: 50.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10
#TODO change back when new model is trained

# kps: [100, 100, 100, 150, 40, 40, 100, 100, 100, 150, 40, 40]
# kds: [2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2]
kps: [100, 100, 100, 150, 40, 40, 100, 100, 100, 150, 40, 40, 300, 100, 100, 50, 50, 20, 100, 100, 50, 50, 20]
kds: [2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2, 3, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1]
# kps: [200, 150, 150, 200, 20, 20, 200, 150, 150, 200, 20, 20, 200, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40]
# kds: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]

# default_angles: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0, 
#                   -0.1,  0.0,  0.0,  0.3, -0.2, 0.0]
# default_angles: [
# -0.2, 0.0, 0.0, 0.42, -0.23, 0.0,
#  -0.2, 0.0, 0.0, 0.42, -0.23, 0.0,
#   0.0, 
#   0.35, 0.16, 0.0, 0.87, 0.0,
#   0.35, -0.16, 0.0, 0.87 ,0.0]
default_angles: [
 -0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
 -0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
  0.0, 
  0.35, 0.16, 0.0, 0.87, 0.0,
  0.35, -0.16, 0.0, 0.87 ,0.0]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
#TODO change back when new model is trained
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25] 
# action_scale: 0.5
# cmd_scale: [1.0, 1.0, 1.0]
num_actions: 23
num_obs: 80

# cmd_init: [0.08, 0.01, 0]
cmd_init: [0.0, 0.0, 0.0]

isaac_mujoco_conversion: True